Generated beta models and request builders
microsoftgraph/msgraph-beta-sdk-go pull request #244
Opened 2023-03-07 10:38 UTC by andrueastman

This pull request was automatically created by Azure Pipelines. **Important** Check for unexpected deletions or changes in this PR.

2023-03-07 14:42 UTC, baywet requested changes
@rkodev to investigate the build failure

2023-03-09 11:40 UTC, rkodev approved these changes

2023-03-09 11:44 UTC, baywet approved these changes
@rkodev what was the issue?

2023-03-09 11:51 UTC, rkodev commented
@baywet the version GO compiler used by the CI seems to have an issue with compiling the `admin_window` code when it exists on its own file. Still not sure why but its possible that there is a bug with the compiler in some host environments. The only change made was to move all the content from `models.admin_window.go` to `models.adim.go`. A root cause anaylsis for this behavior is still pending.

2023-03-09 11:56 UTC, merged